import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from './layout.module.scss'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className={styles.nav}>
          <ul>
            <li>
              <Link href='/'>Checkbox (input visible)</Link>
            </li>
            <li>
              <Link href='/checkbox-input-hidden'>Checkbox (input hidden)</Link>
            </li>
            <li>
              <Link href='/json-explorer'>JSON Explorer</Link>
            </li>
          </ul>
        </nav>
        <main className={styles.main}>
          <div className={styles.description}>{children}</div>
        </main>
      </body>
    </html>
  )
}
